import type { TeacherInput, ParentOpinion, ConsentForm } from './types';

export const defaultTeacherInput: TeacherInput = {
  schoolName: '',
  studentName: '',
  grade: '',
  classNum: '',
  semester: '1',
  year: '2026',
  teacherName: '',
  teacherPhone: '',
  consultTime: '평일 오후 4시~5시',
  meetingDate: '',
  meetingDay: '',
  meetingAmPm: '오후',
  meetingHour: '',
  meetingMinute: '',
  meetingPlace: '',
  submissionDeadline: '',
  submissionDay: '',
  principalName: '',
  adminTeacherName: '',
  schoolAddress: '',
};

export const defaultParentOpinion: ParentOpinion = {
  studentName: '',
  birthDate: '',
  guardianName: '',
  guardianRelation: '',
  guardianRelationOther: '',
  guardianPhone: '',
  writeDate: '',
  disabilityRegistration: '',
  primaryDisability: '',
  secondaryDisability: '',
  secondaryDisabilityType: '',
  disabilitySeverity: '',
  firstRegistrationDate: '',
  specialEdSelection: '',
  specialEdArea: '',
  firstSelectionDate: '',
  currentPlacement: '',
  primaryCaregiver: '',
  primaryCaregiverOther: '',
  siblings: '',
  siblingTotal: '',
  siblingOrder: '',
  siblingDisability: '',
  multicultural: '',
  multiculturalLanguage: '',
  afterSchoolCare: '',
  afterSchoolCareOther: '',
  attendanceMethod: '',
  availableTime: '',
  hasMedication: '',
  medications: [{ name: '', dosage: '', time: '' }],
  schoolMedicationSupport: '',
  allergies: [],
  allergyFoodDetail: '',
  allergyDrugDetail: '',
  allergyEnvDetail: '',
  hasSeizure: '',
  seizureRecent: '',
  seizureInstruction: '',
  dietaryRestriction: [],
  dietaryDiseaseDetail: '',
  dietaryCultureDetail: '',
  sleepCharacteristics: [],
  sensoryIssues: [],
  sensoryOther: '',
  assistiveTech: [],
  assistiveTechOther: '',
  assistiveDevice: [],
  assistiveDeviceOther: '',
  envModification: [],
  envModificationOther: '',
  strengths: '',
  uniqueTraits: '',
  levelLearning: '',
  levelCommunication: '',
  levelSocial: '',
  levelSelfCare: '',
  levelMotor: '',
  levelBehavior: '',
  priorityGoal: '',
  preferredMethod: '',
  evaluationOpinion: '',
  homeConnection: '',
  afterSchoolActivity: '',
  therapyServices: [{ institution: '', area: '', type: '' }],
  afterSchoolSpecialEd: '',
  transportSupport: '',
  assistantSupport: '',
  therapySupportInstitution: '',
  therapySupportArea: '',
  rehabServiceInstitution: '',
  rehabServiceArea: '',
  survivalSwimming: '',
  survivalSwimmingReason: '',
  openClassObservation: '',
  fieldTrip: '',
  fiveYearVision: '',
  careerDirection: '',
  careerDirectionOther: '',
  educationValue: '',
  preferredContact: [],
  availableTimeSlot: [],
  emergencyContact2Name: '',
  emergencyContact2Relation: '',
  emergencyContact2Phone: '',
  healthChanges: '',
  familyChanges: '',
  messageToTeacher: '',
};

export const defaultConsentForm: ConsentForm = {
  consent1: null,
  consent2: null,
  consent3: null,
  consent4_iep: null,
  consent4_curriculum: null,
  consent4_services: null,
  consent4_records: null,
  consent4_handover: null,
  notice5_teaching: false,
  notice5_meal: false,
  notice5_restroom: false,
  notice5_mobility: false,
  notice5_commute: false,
  notice5_note: '',
  consent6_photoRecord: null,
  consent6_internalUse: null,
  consent6_parentShare: null,
  consent6_homepage: null,
  consent6_sns: null,
  consent6_classChannel: null,
  consent7_supervision: null,
  consent7_parentOpen: null,
  consent7_peerObservation: null,
  consent7_competition: null,
  consent7_externalMaterial: null,
  consent8_specialFieldTrip: null,
  consent8_regularFieldTrip: null,
  consent8_events: null,
  consent8_publicTransport: null,
  consent8_insurance: null,
  consent9_firstAid: null,
  consent9_119: null,
  consent9_priorTreatment: null,
  consent9_healthRoom: null,
  emergencyContacts: [
    { name: '', relation: '', phone: '' },
    { name: '', relation: '', phone: '' },
    { name: '', relation: '', phone: '' },
  ],
  consent10_counseling: null,
  consent10_wee: null,
  consent10_assessment: null,
  consent10_iepUse: null,
  consent11_anonymousCase: null,
  consent11_participation: null,
  consent12_statistics: null,
  consent12_research: null,
  consentGuardianName: '',
  consentGuardianRelation: '',
  consentDate: '',
};
