import { FullFormData, TeacherInput, ParentOpinion, ConsentForm } from "./types";

export const defaultTeacherInput: TeacherInput = {
  schoolName: "",
  schoolAddress: "",
  principalName: "",
  adminTeacherName: "",
  studentName: "",
  grade: "",
  classNum: "",
  year: new Date().getFullYear().toString(),
  semester: new Date().getMonth() < 7 ? "1" : "2",
  teacherName: "",
  teacherPhone: "",
  consultTime: "",
  meetingStartDate: "",
  meetingEndDate: "",
  meetingPlace: "",
  submissionDeadline: "",
  submissionDay: "",
};

export const defaultParentOpinion: ParentOpinion = {
  studentName: "",
  birthDate: "",
  guardianName: "",
  guardianRelation: "",
  guardianRelationOther: "",
  guardianPhone: "",

  disabilityRegistration: "",
  primaryDisability: "",
  secondaryDisability: "없음",
  secondaryDisabilityType: "",
  disabilitySeverity: "",
  firstRegistrationDate: "",

  specialEdSelection: "선정",
  specialEdArea: "",
  firstSelectionDate: "",
  currentPlacement: "",

  primaryCaregiver: "부모 공동 양육",
  primaryCaregiverOther: "",
  siblings: "없음(외동)",
  siblingTotal: "",
  siblingOrder: "",
  siblingDisability: "없음",
  multicultural: "해당 없음",
  multiculturalLanguage: "",
  afterSchoolCare: "",
  afterSchoolCareOther: "",

  attendanceMethod: "대면 참석",
  availableTime: "",
  hopeDate1: "",
  hopeTime1: "",
  hopeDate2: "",
  hopeTime2: "",
  hopeDate3: "",
  hopeTime3: "",
  preferredContact: [],
  availableTimeSlot: [],
  emergencyContact2Name: "",
  emergencyContact2Relation: "",
  emergencyContact2Phone: "",

  hasMedication: "없음",
  medications: [],
  schoolMedicationSupport: "필요 없음",
  allergies: [],
  allergyFoodDetail: "",
  allergyDrugDetail: "",
  allergyEnvDetail: "",
  hasSeizure: "없음",
  seizureRecent: "",
  seizureInstruction: "",
  dietaryRestriction: [],
  dietaryDiseaseDetail: "",
  dietaryCultureDetail: "",
  sleepCharacteristics: [],
  sensoryIssues: [],
  sensoryOther: "",

  assistiveTech: [],
  assistiveTechOther: "",
  assistiveDevice: [],
  assistiveDeviceOther: "",
  envModification: [],
  envModificationOther: "",

  strengths: "",
  uniqueTraits: "",

  levelLearning: "",
  levelCommunication: "",
  levelSocial: "",
  levelSelfCare: "",
  levelMotor: "",
  levelBehavior: "",

  priorityGoal: "",
  preferredMethod: "",
  evaluationOpinion: "",
  homeConnection: "",

  afterSchoolActivity: "",
  therapyServices: [],

  afterSchoolSpecialEd: "이용하지 않음",
  afterSchoolSpecialEdInSchool: "",
  afterSchoolSpecialEdOutSchool: "",
  transportSupport: "해당 없음",
  assistantSupport: "필요 없음",
  therapySupportInstitution: "",
  therapySupportDays: "",
  therapySupportArea: "",
  rehabServiceInstitution: "",
  rehabServiceDays: "",
  rehabServiceArea: "",

  survivalSwimming: "",
  survivalSwimmingReason: "",
  openClassObservation: "",
  fieldTrip: "",

  fiveYearVision: "",
  careerDirection: "",
  careerDirectionOther: "",
  educationValue: "",

  healthChanges: "",
  familyChanges: "",
  messageToTeacher: "",

  writeDate: "",
};

export const defaultConsentForm: ConsentForm = {
  consentGuardianName: "",
  consentGuardianRelation: "",
  consentDate: "",

  consent1: null,
  consent2: null,
  consent3: null,
  consent4_iep: null,
  consent4_curriculum: null,
  consent4_services: null,
  consent4_records: null,
  consent4_handover: null,

  notice5_teaching: false,
  notice5_meal: false,
  notice5_restroom: false,
  notice5_mobility: false,
  notice5_commute: false,
  notice5_note: "",

  consent6_photoRecord: null,
  consent6_internalUse: null,
  consent6_parentShare: null,
  consent6_homepage: null,
  consent6_sns: null,
  consent6_classChannel: null,

  consent7_supervision: null,
  consent7_parentOpen: null,
  consent7_peerObservation: null,
  consent7_competition: null,
  consent7_externalMaterial: null,

  consent8_specialFieldTrip: null,
  consent8_regularFieldTrip: null,
  consent8_events: null,
  consent8_publicTransport: null,
  consent8_insurance: null,

  consent9_firstAid: null,
  consent9_119: null,
  consent9_priorTreatment: null,
  consent9_healthRoom: null,
  emergencyContacts: [],

  consent10_counseling: null,
  consent10_wee: null,
  consent10_assessment: null,
  consent10_iepUse: null,

  consent11_anonymousCase: null,
  consent11_participation: null,

  consent12_statistics: null,
  consent12_research: null,
};

export const initialFullData: FullFormData = {
  teacher: defaultTeacherInput,
  opinion: defaultParentOpinion,
  consent: defaultConsentForm,
};
